a10pepo/EDEM_MDA2425

ALUMNOS/MDAB/VALENTIN_VECHER/README.md
=> VALENTIN_VERCHER

ALUMNOS/MIA/ALEJANDRO_VEINTIMILLA/README.md
=> Añadir Alejandro Veintimilla

ALUMNOS/MDAB/CARLOS_OLIVER/README.md
=> GITHUB_CARLOS

ALUMNOS/MDAB/ANGEL_MARTINEZ/README.md
Readme de prueba
- [ x] He probado mi código y funciona en local
- [ x] He validado que mi código es correcto a niveles de formato
- [ x] Me he asegurado de no haber comiteado o filtrado ninguna contraseña
- [ x] No he copiado mi código porque soy una persona muy responsable :-)
=> Angel Martínez

ALUMNOS/MDAB/MARC_CANTERO/README.md, README.md
=> CARPETA Y README nuevo

ALUMNOS/MIA/ANDREU_PICORNELL/README.md
=> Added readme Andreu

ALUMNOS/MDAB/JOEL_SEGUI/README.md, README.md
=> Demo joel1091

ALUMNOS/MDAA/JOAN_GILABERT/README.md
=> Creación Carpeta

ALUMNOS/MDAA/ALEJANDRO_ESCOLANO/README.md
=> creacion de carpeta

ALUMNOS/MDAA/IGNACIO_VALERO/README.md, main.py
=> Creación de Carpeta

ALUMNOS/MDAA/MAR_SOLER/DEMO/entregable.md
=> entrega demo

ALUMNOS/MDAA/ANTONI_MOLLA/DEMO/Entregable.md
=> Carpeta Entregable

ALUMNOS/MDAA/IGNACIO_VALERO/README.md
=> Actualizacion

ALUMNOS/MDAA/MAR_SOLER/DEMO/entregable.md
=> cambios251005

ALUMNOS/MDAA/MIGUEL_TORRES/README.md
=> Modificación del readme

ALUMNOS/MDAB/TING_WANG/README.md
He subido mi README.md
Segundo intento:
=> Ting's README.md

ALUMNOS/MDAB/CLAUDIA_/README.md
=> Actualización README

ALUMNOS/MDAB/JOAQUIN_ZAPATA/README.md
=> readme demo 1

ALUMNOS/MIA/JOSE_BARBERO/README.md, README.md
=> jobarbru_README.md

ALUMNOS/MDAB/JUAN_MONTOLIU/README.MD
CREACION DE CARPETA Y MI README
=> JMontoliu carpeta y readme

ALUMNOS/MDAA/VICENTE_MARTI/EjercicioLinux.md, ALUMNOS/MDAA/VICENTE_MARTI/README.md
=> Entregable Linux

ALUMNOS/MIA/COKE_STUYCK/LINUX/README.md
=> Completed LINUX exercise

ALUMNOS/MIA/PAU_JORQUES/LINUX/README.md
=> Entrega Linux

ALUMNOS/MDAA/ALEX_REVERT/LINUX
=> EJERCICIO LINUX

ALUMNOS/MIA/ANDREU_PICORNELL/LINUX/README.md
=> Anpibo linux

ALUMNOS/MIA/MAURO_BALAGUER/LINUX/README.md
=> Linux - Maurobalas

ALUMNOS/MIA/PABLO_ARNAU/LINUX/README.md
=> ejercicio_linux

ALUMNOS/MDAA/MIGUEL_TORRES/LINUX/README.md
Entregable del ejercicio de linux
=> Entrega linux Miguel Torres

ALUMNOS/MDAB/MARC_CANTERO/LINUX/tarea.md, ALUMNOS/MDAB/MARC_CANTERO/lLINUX/tarea.md
=> LINUX_Marc

ALUMNOS/MDAA/ALEX_REVERT/LINUX/README.md
=> He corregido un fallo que tenía en el código

ALUMNOS/MIA/JOSE_BARBERO/LINUX/LINUX.md
=> jobarbru_LINUX

ALUMNOS/MDAB/CARLOS_OLIVER/LINUX/linux_carlos_oliver.md
=> rama_linux

ALUMNOS/MIA/RAFA_ORTEGA/LINUX/README.md
=> EJERCICIO LINUX RAFA ORTEGA

.github/CODEOWNERS, .github/labeler.yml, .github/workflows/pr_check.yaml, ALUMNOS/MDAA/PEDRO_NIETO/LINUX/README.md
=> add labeler

ALUMNOS/MDAB/ALEJANDRO_BOSCH/SQL/SESION_01_SQL.md
=> SESION_01_SQL

ALUMNOS/MIA/PABLO_ARNAU/SQL/clase1_sql.txt
=> primera sesión sql

ALUMNOS/MDAB/CARLOS_OLIVER/SQL/querys.txt
=> entrega_sql

ALUMNOS/MDAB/VALENTIN_VECHER/SQL/film_clase_d1.sql, ALUMNOS/MDAB/VALENTIN_VECHER/SQL/film_clase_d2.sql
estos son todos los pasos y ejercicios explicados que hicimos en clase
=> apuntes y ejercicios hechos en clase

.github/CODEOWNERS, .github/labeler.yml
=> Fix assigned

PROFESORES/MDA/CHAT/chatcode/chatbot.py
=> E2 e modulo12

ALUMNOS/MDAB/FABIAN_MIULESCU/PYTHON/Proyecto_Final/proyecto_final.py, ALUMNOS/MDAB/FABIAN_MIULESCU/PYTHON/Sesion1/Ejercicio1/Ejercicio1.py, ALUMNOS/MDAB/FABIAN_MIULESCU/PYTHON/Sesion1/Ejercicio2/Ejercicio2.py, ALUMNOS/MDAB/FABIAN_MIULESCU/PYTHON/Sesion2/Ejercicio/Ejercicio.py, ALUMNOS/MDAB/FABIAN_MIULESCU/PYTHON/Sesion3/Ejercicio1/Ejercicio1.py, ALUMNOS/MDAB/FABIAN_MIULESCU/PYTHON/Sesion3/Ejercicio2/Ejercicio2.py, ALUMNOS/MDAB/FABIAN_MIULESCU/PYTHON/Sesion3/Ejercicio3/Ejercicio3.py, ALUMNOS/MDAB/FABIAN_MIULESCU/PYTHON/Sesion4/Ejercicio1/Ejercicio1.py, ALUMNOS/MDAB/FABIAN_MIULESCU/PYTHON/Sesion4/Ejercicio2/requirements.txt, ALUMNOS/MDAB/FABIAN_MIULESCU/PYTHON/Sesion4/Ejercicio3/Ejercicio3.py, ALUMNOS/MDAB/FABIAN_MIULESCU/PYTHON/Sesion5/Ejercicio1/Data/pokemon_data.csv, ALUMNOS/MDAB/FABIAN_MIULESCU/PYTHON/Sesion5/Ejercicio1/Ejercicio1.py, ALUMNOS/MDAB/FABIAN_MIULESCU/PYTHON/Sesion5/Ejercicio2y3/Ejercicio2.py, ALUMNOS/MDAB/FABIAN_MIULESCU/PYTHON/Sesion5/Ejercicio2y3/Ejercicio3.py
Entregables del 1 al 5 y el proyecto final
=> Entregables + Proyecto Final

ALUMNOS/MDAB/JOEL_SEGUI/CHUCK/Nifi01.xml, ALUMNOS/MDAB/JOEL_SEGUI/CHUCK/README.md, ALUMNOS/MDAB/JOEL_SEGUI/CHUCK/docker-compose.yml, ALUMNOS/MDAB/JOEL_SEGUI/CHUCK/dockerfile, ALUMNOS/MDAB/JOEL_SEGUI/CHUCK/requirements.txt, ALUMNOS/MDAB/JOEL_SEGUI/CHUCK/script.py
(hay que ejecutar el template de nifi para la injesta previa, sino no funciona
=> E2E_chuck_completed

ALUMNOS/MDAA/MARTA_MIRO/PYTHON/Ejercicio3MartaMiro.py
Hola, subo el ejercicio 3 de python
- [ x] He probado mi código y funciona en local
- [ x] He validado que mi código es correcto a niveles de formato
- [ x] Me he asegurado de no haber comiteado o filtrado ninguna contraseña
- [ x] No he copiado mi código porque soy una persona muy responsable :-)
=> Ejercicio 3 python Marta Miró

ALUMNOS/MDAB/LARA_RUBIO/SQL/Sesion_1.sql
=> sesion1 sql

ALUMNOS/MDAB/ALEJANDRO_BOSCH/TICTACTOE/Dockerfile, ALUMNOS/MDAB/ALEJANDRO_BOSCH/TICTACTOE/README.md, ALUMNOS/MDAB/ALEJANDRO_BOSCH/TICTACTOE/docker-compose.yaml, ALUMNOS/MDAB/ALEJANDRO_BOSCH/TICTACTOE/game.py, ALUMNOS/MDAB/ALEJANDRO_BOSCH/TICTACTOE/requirements.txt
- [ x] He validado que mi código es correcto a niveles de formato
- [ x] Me he asegurado de no haber comiteado o filtrado ninguna contraseña
- [ x] No he copiado mi código porque soy una persona muy responsable :-)
=> alejbc27 - tictactoe

ALUMNOS/MDAB/TING_WANG/TICTACTOE/Dockerfile, ALUMNOS/MDAB/TING_WANG/TICTACTOE/docker-compose.yaml, ALUMNOS/MDAB/TING_WANG/TICTACTOE/game.py
=> e-wach-TICTACTOE

ALUMNOS/MDAA/MIGUEL_TORRES/CHUCK/README.md, ALUMNOS/MDAA/MIGUEL_TORRES/CHUCK/docker-compose.yml, ALUMNOS/MDAA/MIGUEL_TORRES/CHUCK/python-migrator/Dockerfile, ALUMNOS/MDAA/MIGUEL_TORRES/CHUCK/python-migrator/migrate.py, ALUMNOS/MDAA/MIGUEL_TORRES/CHUCK/python-migrator/requirements.txt
=> Chuck_Miguel_Torres

ALUMNOS/MDAB/ANGEL_MARTINEZ/PYTHON/Proyecto_final/Proyecto_final.py, ALUMNOS/MDAB/ANGEL_MARTINEZ/PYTHON/Sesión_1/Ejercició 1/Ejercicio1.py, ALUMNOS/MDAB/ANGEL_MARTINEZ/PYTHON/Sesión_1/Ejercició 2/Ejercicio2.py, ALUMNOS/MDAB/ANGEL_MARTINEZ/PYTHON/Sesión_2/Ejercicio2.py, ALUMNOS/MDAB/ANGEL_MARTINEZ/PYTHON/Sesión_3/Ejercicio1/Ejercicio1.py, ALUMNOS/MDAB/ANGEL_MARTINEZ/PYTHON/Sesión_3/Ejercicio2/Ejercicio2.py, ALUMNOS/MDAB/ANGEL_MARTINEZ/PYTHON/Sesión_3/Ejercicio3/Ejercicio3.py, ALUMNOS/MDAB/ANGEL_MARTINEZ/PYTHON/Sesión_4/Ejercicio1/Ejercicio1.py, ALUMNOS/MDAB/ANGEL_MARTINEZ/PYTHON/Sesión_4/Ejercicio1/Ejercicio2.py, ALUMNOS/MDAB/ANGEL_MARTINEZ/PYTHON/Sesión_4/Ejercicio1/Ejercicio3.py, ALUMNOS/MDAB/ANGEL_MARTINEZ/PYTHON/Sesión_4/Ejercicio2/requirements.txt, ALUMNOS/MDAB/ANGEL_MARTINEZ/PYTHON/Sesión_4/Ejercicio3/Ejercicio3.py, ALUMNOS/MDAB/ANGEL_MARTINEZ/PYTHON/Sesión_5/Ejercicio_1/Ejercicio1.py, ALUMNOS/MDAB/ANGEL_MARTINEZ/PYTHON/Sesión_5/Ejercicio_1/pokemon_data.csv, ALUMNOS/MDAB/ANGEL_MARTINEZ/PYTHON/Sesión_5/Ejercicio_2/Ejercicio2.py, ALUMNOS/MDAB/ANGEL_MARTINEZ/PYTHON/Sesión_5/Ejercicio_3/Ejercicio1.py
- [ x] Me he asegurado de no haber comiteado o filtrado ninguna contraseña
- [ x] No he copiado mi código porque soy una persona muy responsable :-)
=> Python-Angel

ALUMNOS/MDAA/MAR_SOLER/README.md
=> Update README.md Mar

ALUMNOS/MIA/ALBERTO_GARCIA/PYTHON/Curso de Python/ProyectoFinal.py, ALUMNOS/MIA/ALBERTO_GARCIA/PYTHON/Curso de Python/Sesión 1/Ejercicio 1.py, ALUMNOS/MIA/ALBERTO_GARCIA/PYTHON/Curso de Python/Sesión 1/Ejercicio 2.py, ALUMNOS/MIA/ALBERTO_GARCIA/PYTHON/Curso de Python/Sesión 2/Ejercicio 1.py, ALUMNOS/MIA/ALBERTO_GARCIA/PYTHON/Curso de Python/Sesión 3/Ejercicio 1.py, ALUMNOS/MIA/ALBERTO_GARCIA/PYTHON/Curso de Python/Sesión 3/Ejercicio 2.py, ALUMNOS/MIA/ALBERTO_GARCIA/PYTHON/Curso de Python/Sesión 3/Ejercicio 3.py, ALUMNOS/MIA/ALBERTO_GARCIA/PYTHON/Curso de Python/Sesión 4/Ejercicio 1.py, ALUMNOS/MIA/ALBERTO_GARCIA/PYTHON/Curso de Python/Sesión 4/Ejercicio 2.py, ALUMNOS/MIA/ALBERTO_GARCIA/PYTHON/Curso de Python/Sesión 4/Ejercicio 3.py, ALUMNOS/MIA/ALBERTO_GARCIA/PYTHON/Curso de Python/Sesión 5/Ejercicio1.py, ALUMNOS/MIA/ALBERTO_GARCIA/PYTHON/Curso de Python/Sesión 5/Ejercicio2.py, ALUMNOS/MIA/ALBERTO_GARCIA/PYTHON/Curso de Python/Sesión 5/Ejercicio3.py
Añado todos los ejercicios por sesión, además del proyecto final
- [ x] He probado mi código y funciona en local
=> Entregas Python Alberto García

README.md
=> fixing main

PROFESORES/MIA/ML3_CLUSTERING/README.md
Enunciado del ejercicio de clustering y dimensionalidad del MIA
=> enunciado de clustering y dimensionalidad

ALUMNOS/MDAB/JOAQUIN_ZAPATA/Python/Proyecto Final/Proyecto_Final.py, ALUMNOS/MDAB/JOAQUIN_ZAPATA/Python/Sesion 1/Ejercicio 1.py, ALUMNOS/MDAB/JOAQUIN_ZAPATA/Python/Sesion 1/Ejercicio 2.py, ALUMNOS/MDAB/JOAQUIN_ZAPATA/Python/Sesion 2/Ejercicio 1.py, ALUMNOS/MDAB/JOAQUIN_ZAPATA/Python/Sesion 3/Ejercicio 1.py, ALUMNOS/MDAB/JOAQUIN_ZAPATA/Python/Sesion 3/Ejercicio 2.py, ALUMNOS/MDAB/JOAQUIN_ZAPATA/Python/Sesion 3/Ejercicio 3.py, ALUMNOS/MDAB/JOAQUIN_ZAPATA/Python/Sesion 4/Ejercicio 1.py, ALUMNOS/MDAB/JOAQUIN_ZAPATA/Python/Sesion 4/Ejercicio 2.py, ALUMNOS/MDAB/JOAQUIN_ZAPATA/Python/Sesion 4/Ejercicio 3.py, ALUMNOS/MDAB/JOAQUIN_ZAPATA/Python/Sesion 5/Ejercicio 1.py, ALUMNOS/MDAB/JOAQUIN_ZAPATA/Python/Sesion 5/Ejercicio 2.py, ALUMNOS/MDAB/JOAQUIN_ZAPATA/Python/Sesion 5/Ejercicio 3.py, ALUMNOS/MDAB/JOAQUIN_ZAPATA/Python/Sesion 5/pokemon_data.csv
=> Joaquin-Entrega python

.github/CODEOWNERS
=> Add yaling

PROFESORES/MIA/RN2_CNN/Deliverable_CNN.ipynb
=> Add CNN deliverable

.github/labeler.yml
=> adding labeler

.github/code/check.py
=> adding modulo 1

ALUMNOS/MIA/IGNACIO_MARTINEZ/PYTHON/PROYECTO_FINAL/archivo13.py, ALUMNOS/MIA/IGNACIO_MARTINEZ/PYTHON/SESION 1/Ejercicio_1/archivo1.py, ALUMNOS/MIA/IGNACIO_MARTINEZ/PYTHON/SESION 1/Ejercicio_2/archivo2.py, ALUMNOS/MIA/IGNACIO_MARTINEZ/PYTHON/SESION 2/Ejercicio_1/archivo3.py, ALUMNOS/MIA/IGNACIO_MARTINEZ/PYTHON/SESION 3/Ejercicio_1/archivo4.py, ALUMNOS/MIA/IGNACIO_MARTINEZ/PYTHON/SESION 3/Ejercicio_2/archivo5.py, ALUMNOS/MIA/IGNACIO_MARTINEZ/PYTHON/SESION 3/Ejercicio_3/archivo6.py, ALUMNOS/MIA/IGNACIO_MARTINEZ/PYTHON/SESION 4/Ejercicio_1/archivo7.py, ALUMNOS/MIA/IGNACIO_MARTINEZ/PYTHON/SESION 4/Ejercicio_2/archivo8.py, ALUMNOS/MIA/IGNACIO_MARTINEZ/PYTHON/SESION 4/Ejercicio_3/archivo9.py, ALUMNOS/MIA/IGNACIO_MARTINEZ/PYTHON/SESION 5/Ejercicio_1/archivo10.py, ALUMNOS/MIA/IGNACIO_MARTINEZ/PYTHON/SESION 5/Ejercicio_1/pokemon_data.csv, ALUMNOS/MIA/IGNACIO_MARTINEZ/PYTHON/SESION 5/Ejercicio_2/archivo11.py, ALUMNOS/MIA/IGNACIO_MARTINEZ/PYTHON/SESION 5/Ejercicio_3/archivo12.py
=> Python_Entregable_Namase7

ALUMNOS/MDAB/TING_WANG/PYTHON/PROYECTO-FINAL/funciones.py, ALUMNOS/MDAB/TING_WANG/PYTHON/PROYECTO-FINAL/lista_alumnos.py, ALUMNOS/MDAB/TING_WANG/PYTHON/PROYECTO-FINAL/mensaje.txt, ALUMNOS/MDAB/TING_WANG/PYTHON/PROYECTO-FINAL/proyecto_final.py
=> Proyecto-final PYTHON

ALUMNOS/MDAB/CARLOS_OLIVER/PYTHON/Proyecto_Final/proyecto_final.py, ALUMNOS/MDAB/CARLOS_OLIVER/PYTHON/Sesion1/Ejercicio1/Ejercicio1.py, ALUMNOS/MDAB/CARLOS_OLIVER/PYTHON/Sesion1/Ejercicio2/Ejercicio2.py, ALUMNOS/MDAB/CARLOS_OLIVER/PYTHON/Sesion2/Ejercicio.py, ALUMNOS/MDAB/CARLOS_OLIVER/PYTHON/Sesion3/Ejercicio1/Ejercicio1.py, ALUMNOS/MDAB/CARLOS_OLIVER/PYTHON/Sesion3/Ejercicio2/Ejercicio2.py, ALUMNOS/MDAB/CARLOS_OLIVER/PYTHON/Sesion3/Ejercicio3/Ejercicio3.py, ALUMNOS/MDAB/CARLOS_OLIVER/PYTHON/Sesion4/Ejercicio1/Ejercicio1.py, ALUMNOS/MDAB/CARLOS_OLIVER/PYTHON/Sesion4/Ejercicio2/requirements.txt, ALUMNOS/MDAB/CARLOS_OLIVER/PYTHON/Sesion4/Ejercicio3/Ejercicio3.py, ALUMNOS/MDAB/CARLOS_OLIVER/PYTHON/Sesion5/Ejercicio1/Data/pokemon_data.csv, ALUMNOS/MDAB/CARLOS_OLIVER/PYTHON/Sesion5/Ejercicio1/Ejercicio1.py, ALUMNOS/MDAB/CARLOS_OLIVER/PYTHON/Sesion5/Ejercicio2y3/Ejercicio2.py, ALUMNOS/MDAB/CARLOS_OLIVER/PYTHON/Sesion5/Ejercicio2y3/Ejercicio3.py
=> python_exercises

ALUMNOS/MDAB/CLAUDIA_ROMERO/PYTHON/Entregables/Sesion_1/Ejercicio_1/Ejercicio_1.py, ALUMNOS/MDAB/CLAUDIA_ROMERO/PYTHON/Entregables/Sesion_1/Ejercicio_2/Ejercicio_2.py, ALUMNOS/MDAB/CLAUDIA_ROMERO/PYTHON/Entregables/Sesion_2/Ejercicio/Ejercicio.py, ALUMNOS/MDAB/CLAUDIA_ROMERO/PYTHON/Entregables/Sesion_3/Ejercicio_1/Ejercicio_1.py, ALUMNOS/MDAB/CLAUDIA_ROMERO/PYTHON/Entregables/Sesion_3/Ejercicio_2/Ejercicio_2.py, ALUMNOS/MDAB/CLAUDIA_ROMERO/PYTHON/Entregables/Sesion_3/Ejercicio_3/Ejercicio_3.py, ALUMNOS/MDAB/CLAUDIA_ROMERO/PYTHON/Entregables/Sesion_4/Ejercicio_1/Ejercicio_1.py, ALUMNOS/MDAB/CLAUDIA_ROMERO/PYTHON/Entregables/Sesion_4/Ejercicio_2/requirements.txt, ALUMNOS/MDAB/CLAUDIA_ROMERO/PYTHON/Entregables/Sesion_4/Ejercicio_3/Ejercicio_3.py, ALUMNOS/MDAB/CLAUDIA_ROMERO/PYTHON/Entregables/Sesion_5/Ejercicio_1/Ejercicio_1.py, ALUMNOS/MDAB/CLAUDIA_ROMERO/PYTHON/Entregables/Sesion_5/Ejercicio_1/pokemon_data.csv, ALUMNOS/MDAB/CLAUDIA_ROMERO/PYTHON/Entregables/Sesion_5/Ejercicio_2_y_3/Ejercicio_2.py, ALUMNOS/MDAB/CLAUDIA_ROMERO/PYTHON/Entregables/Sesion_5/Ejercicio_2_y_3/Ejercicio_3.py, ALUMNOS/MDAB/CLAUDIA_ROMERO/PYTHON/Proyecto_final/proyecto_final.py
=> Ejercicios_python

ALUMNOS/MDAB/CARLOS_OLIVER/APIS/README.md, ALUMNOS/MDAB/CARLOS_OLIVER/APIS/robot_sensor_api.yaml
=> api_exercises

PROFESORES/MIA/MLOPS/README.md, PROFESORES/MIA/MLOPS/model-registry/mlflow-basics.ipynb, PROFESORES/MIA/MLOPS/model-registry/mlflow-training.ipynb, PROFESORES/MIA/MLOPS/model-registry/requeriments.txt, PROFESORES/MIA/MLOPS/model-servers/fast-api-server/app/app.py, PROFESORES/MIA/MLOPS/model-servers/fast-api-tutorial/app/app.py, PROFESORES/MIA/MLOPS/model-servers/fast-api-vertex/Dockerfile, PROFESORES/MIA/MLOPS/model-servers/fast-api-vertex/docker-instructions.sh, PROFESORES/MIA/MLOPS/model-servers/fast-api-vertex/push-docker-gcp.sh, PROFESORES/MIA/MLOPS/model-servers/fast-api-vertex/requirements.txt, PROFESORES/MIA/MLOPS/model-servers/mlserver/00-basic/sklearn-basic-example.ipynb, PROFESORES/MIA/MLOPS/model-servers/mlserver/01-custom/custom-example.ipynb, PROFESORES/MIA/MLOPS/model-servers/mlserver/01-custom/models.py, PROFESORES/MIA/MLOPS/model-servers/requirements.txt, PROFESORES/MIA/MLOPS/model-servers/train-simple-model.py, PROFESORES/MIA/MLOPS/pipelines/kubeflow_exercise.ipynb, PROFESORES/MIA/MLOPS/pipelines/kubeflow_tutorial.ipynb, PROFESORES/MIA/MLOPS/pipelines/metaflow-basics.ipynb, PROFESORES/MIA/MLOPS/pipelines/metaflow-model-training.ipynb, PROFESORES/MIA/MLOPS/pipelines/requirements.txt
Código de soporte y ejercicios para el módulo de MLOps de MIA.
Saludos.
=> codigo de soporte y ejercicios de MLOps

PROFESORES/MDA/AWS_ESPECIFICOS/NUKE/aws-nuke.md, PROFESORES/MDA/AWS_ESPECIFICOS/NUKE/nuke-config.yaml
=> adding nuke

PROFESORES/MDA/AWS_ALMACENAMIENTO/README.md, PROFESORES/MDA/AWS_ALMACENAMIENTO/initial_info.py
=> [ADDED] Adding instructions for entregable AWS Almacenamiento

ALUMNOS/MDAB/CLAUDIA_ROMERO/APIS/Ejercicio1.yaml
=> Ejercicio APIS

ALUMNOS/MDAA/MIGUEL_TORRES/APIS/API_ROBOT.yaml, ALUMNOS/MDAA/MIGUEL_TORRES/APIS/README.md
=> Entregable APIS Miguel

ALUMNOS/MIA/JAIME_OLANO/PYTHON/proyecto final/proyecto_final.py
=> PROYECTO FINAL PY

ALUMNOS/MDAA/ALEJANDRO_ESCOLANO/APIS/sensor-api.yaml
=> Aesctor api

ALUMNOS/MDAA/VICENTE_MARTI/APIS/ejercicio_api.yaml
- [ x] He probado mi código y funciona en local
=> Ejercicio API

.github/labeler.yml
=> adding label

ALUMNOS/MDAB/FABIAN_MIULESCU/APIS/openapi.yaml
=> Add OpenAPI specification for Robot Temperature Sensor API

ALUMNOS/MDAA/JUAN_BESSINI/PYTHON/SESION_1/ejercicio_1.py, ALUMNOS/MDAA/JUAN_BESSINI/PYTHON/SESION_1/ejercicio_2.py, ALUMNOS/MDAA/JUAN_BESSINI/PYTHON/SESION_2/ejercicio_1.py, ALUMNOS/MDAA/JUAN_BESSINI/PYTHON/SESION_3/ejercicio_1.py, ALUMNOS/MDAA/JUAN_BESSINI/PYTHON/SESION_3/ejercicio_2.py, ALUMNOS/MDAA/JUAN_BESSINI/PYTHON/SESION_3/ejercicio_3.py, ALUMNOS/MDAA/JUAN_BESSINI/PYTHON/SESION_4/ejercicio_1.py, ALUMNOS/MDAA/JUAN_BESSINI/PYTHON/SESION_4/ejercicio_2/ejercicio_2.py, ALUMNOS/MDAA/JUAN_BESSINI/PYTHON/SESION_4/ejercicio_2/requirements.txt, ALUMNOS/MDAA/JUAN_BESSINI/PYTHON/SESION_4/ejercicio_3.py
=> Entregable_Python

ALUMNOS/MDAA/MIGUEL_TORRES/AWS_ALMACENAMIENTO/README.md, ALUMNOS/MDAA/MIGUEL_TORRES/AWS_ALMACENAMIENTO/el_lakehouse.py, ALUMNOS/MDAA/MIGUEL_TORRES/AWS_ALMACENAMIENTO/el_redshift.py, ALUMNOS/MDAA/MIGUEL_TORRES/AWS_ALMACENAMIENTO/initial_info.py, ALUMNOS/MDAA/MIGUEL_TORRES/AWS_ALMACENAMIENTO/main.py, ALUMNOS/MDAA/MIGUEL_TORRES/AWS_ALMACENAMIENTO/requirements.txt, ALUMNOS/MDAA/MIGUEL_TORRES/AWS_ALMACENAMIENTO/schema.sql
=> Entrega tarea AWS Almacenamiento

ALUMNOS/MDAA/JUAN_BESSINI/AWS_ALMACENAMIENTO/README.md, ALUMNOS/MDAA/JUAN_BESSINI/AWS_ALMACENAMIENTO/initial_info.py, ALUMNOS/MDAA/JUAN_BESSINI/AWS_ALMACENAMIENTO/main.py, ALUMNOS/MDAA/JUAN_BESSINI/AWS_ALMACENAMIENTO/requirements.txt
=> Ejercicio_AWS
